/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package riffa_payroll;

import com.mysql.jdbc.Connection;
import com.mysql.jdbc.PreparedStatement;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.ResultSet;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;




/**
 *
 * @author THOMAS
 */
public class Login extends javax.swing.JFrame {
    Connection conn = null;
    ResultSet rs = null;
    PreparedStatement pst = null;

    /** Creates new form Login */
    public Login() {
        initComponents();
        Toolkit toolkit = getToolkit();
        Dimension size = toolkit.getScreenSize();
        setLocation(size.width/2 - getWidth()/2, size.height/2 - getHeight()/2);
        
        
        conn = (Connection) db.java_db();
        currentDate();
        
    }
    
    
    public void currentDate(){
        
        Calendar cal = new GregorianCalendar();
        int Month = cal.get(Calendar.MONTH);
        int Year = cal.get(Calendar.YEAR);
        int Day = cal.get(Calendar.DAY_OF_MONTH);
        
        lbl_date.setText((Month +1)+"/"+Day+"/"+Year);
        
        int Second = cal.get(Calendar.SECOND);
        int Minute = cal.get(Calendar.MINUTE);
        int Hour = cal.get(Calendar.HOUR);
        
        lbl_time.setText(Hour+":"+Minute+":"+Second);
        
    
    
    
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txt_usrnme = new javax.swing.JTextField();
        txt_combo = new javax.swing.JComboBox<>();
        lgnbtn = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txt_psswrd = new javax.swing.JPasswordField();
        jLabel5 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        lbl_date = new javax.swing.JMenu();
        lbl_time = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setLayout(null);

        txt_usrnme.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_usrnmeActionPerformed(evt);
            }
        });
        jPanel1.add(txt_usrnme);
        txt_usrnme.setBounds(180, 190, 140, 30);

        txt_combo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Administration", "Sales" }));
        jPanel1.add(txt_combo);
        txt_combo.setBounds(180, 272, 140, 30);

        lgnbtn.setText("LOGIN");
        lgnbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lgnbtnActionPerformed(evt);
            }
        });
        jPanel1.add(lgnbtn);
        lgnbtn.setBounds(250, 320, 67, 25);

        jLabel4.setText("SELECT DIVISION");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(10, 280, 160, 16);

        jLabel3.setText("PASSWORD");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(10, 240, 160, 16);

        jLabel2.setText("USERNAME");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(10, 200, 160, 16);

        jLabel1.setText("ENTER USERNAME AND PASSWORD TO LOGIN");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(10, 160, 310, 16);
        jPanel1.add(txt_psswrd);
        txt_psswrd.setBounds(180, 230, 140, 30);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/riffa_payroll/images/GettyImages-964033964-ca3290057ccc4024b57e755423572264.jpg"))); // NOI18N
        jLabel5.setText("jLabel5");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(0, 0, 550, 350);

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        lbl_date.setText("Date");
        jMenuBar1.add(lbl_date);

        lbl_time.setText("Time");
        jMenuBar1.add(lbl_time);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 550, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 352, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_usrnmeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_usrnmeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_usrnmeActionPerformed

    private void lgnbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lgnbtnActionPerformed
        // TODO add your handling code here:
        String sql ="select USerId, Username, Password, Division from users where (Username=? and Password=? and Division=?)";
        
        try{
            
            int count = 0;
            
            pst = (PreparedStatement) conn.prepareStatement(sql);
            
            pst.setString(1, txt_usrnme.getText());
            pst.setString(2, txt_psswrd.getText());
            pst.setString(3, txt_combo.getSelectedItem().toString());
            
            rs = pst.executeQuery();
            while(rs.next()){
                int id = rs.getInt(1);
                Employee.empid = id;
                String username = rs.getString("username");
                Employee.empname = username;
                count = count+1;
               
            }
            String access = (txt_combo.getSelectedItem().toString());
            
            if (access == "Administration"){
                if(count==1){
                    JOptionPane.showMessageDialog(null, "success");
                    MainMenu j = new MainMenu();
                    j.setVisible(true);
                    this.dispose();
                    
                   Date currentDate = GregorianCalendar.getInstance().getTime();
                  DateFormat df = DateFormat.getDateInstance();
                  String dateString = df.format(currentDate);

                  Date d = new Date();
                  SimpleDateFormat sdf = new SimpleDateFormat("HH:mm:ss");
                  String timeString = sdf.format(d);

                  String value0 = timeString;
                  String values = dateString;
                   
                   
                   int value = Employee.empid;
                   String reg = "insert into Audit (emp_id,date,status) values ('"+value+"','"+value0+" / "+values+"','Logged in')";
                   pst=(PreparedStatement) conn.prepareStatement(reg);
                   pst.execute();
                   this.dispose();
                 
                }else{
                    JOptionPane.showMessageDialog(null, "Check Login Credentials and Try Again");
                
                }
            
            }
        
        }catch (Exception e){
            JOptionPane.showMessageDialog(null, e);
        
        }finally{
            try{
                rs.close();
                pst.close();
            
            }catch(Exception e){
            
            }
        
        
        }
        
        
        
    }//GEN-LAST:event_lgnbtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JMenu lbl_date;
    private javax.swing.JMenu lbl_time;
    private javax.swing.JButton lgnbtn;
    private javax.swing.JComboBox<String> txt_combo;
    private javax.swing.JPasswordField txt_psswrd;
    private javax.swing.JTextField txt_usrnme;
    // End of variables declaration//GEN-END:variables

}
